version: '3'
services:
  mysql-container:
    build:
      context: ./sql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", 'mysqladmin','--protocol=TCP', 'ping', '-h', 'localhost', '-u', 'root', '-proot']
      timeout: 10s
      retries: 30
  nginx-container:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
  python:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      mysql-container:
        condition: service_healthy
